name: kiwifig
description: computer vision and computer graphic digger 

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            kiwifig
tagline:          'A image matrix digger'
description:      'computer vision and computer graphic digger .'

author:
  name:           'kiwi'
  url:            http://kiwifig.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kiwifig
