# Site settings
title: kiwifig
description: "Computer vision and computer graphic digger."
url: "http://kiwifig.github.io"
author:
  name: "kiwifig"
  email: "kiwifig@gmail.com"
  url: "http://kiwifig.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: redcarpet
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
